# This is a basic workflow to help you get started with Actions

name: uploadArtifact

# Controls when the workflow will run
on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout code
        uses: actions/checkout@v2
      - name: upload artfact
        uses: actions/upload_artifacts@v2
        with:
         name: ${{env.ARTIFACT_NAME}}
         path: .
        

      
